spring.application.name=discovery-service
server.port=8761

# Ne s'enregistre pas lui-meme
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Demarre sans dependre de personne
spring.cloud.config.enabled=false

# Securite - Dev
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
# Prod
#eureka.server.enable-self-preservation=true

eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=health,refresh,info