spring.application.name=discovery-service
server.port=8761
# do not register server itself as a client.
eureka.client.fetch-registry=false
# Does not register itself in the service registry.
eureka.client.register-with-eureka=false
spring.cloud.config.enabled=false
# Enregister les client eureka par son adresse IP
eureka.instance.prefer-ip-address=true
# ou se trouve eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka