spring.application.name=config-service
server.port=9999
spring.cloud.discovery.enabled=true
spring.cloud.config.server.git.uri=file://D:/2025-2026-supmti/MicroService/bank_account_micro_service_app/Config-Repo